services:
  postgres:
    image: postgres:14
    container_name: andarna_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: andarna_local_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: olya@andarna.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: